name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.9.4
  - pandas=2.2.3
  - pip=24.3.1
  - scikit-learn=1.6.0
  - jupyterlab=4.3.4
  - ydata-profiling=4.12.1
  - ipywidgets=8.1.5
  - pip:
      - mlflow==2.19
      - wandb==0.19.1